export const inputHabitationFull = form.querySelector("[data-address='full']");
export const addressList = form.querySelector("[data-address-list]");
export const inputVille = form.querySelector("[data-empty-ville]");
export const inputCodePostal = form.querySelector("[data-empty-codepostal]");
export const inputNumberStreet = form.querySelector("[data-empty-numberstreet]");
export const textAddress = form.querySelector("[data-address-item]");
export const parent = textAddress.parentNode;
export const addressText = "[data-adress-label]";
export const addressPostalText = "[data-adress-postal]";
