export const inputHabitationFull = document.querySelector("[data-address='full']");
export const addressList = document.querySelector("[data-address-list]");
export const inputVille = document.querySelector("[data-empty-ville]");
export const inputCodePostal = document.querySelector("[data-empty-codepostal]");
export const inputNumberStreet = document.querySelector("[data-empty-numberstreet]");
export const textAddress = document.querySelector("[data-address-item]");
export const parent = textAddress.parentNode;
export const addressText = "[data-adress-label]";
export const addressPostalText = "[data-adress-postal]";
